### ISSUE TITLE
`ether://` face creation not working

### ISSUE THREAD

**Issue by malldisaesar** [named-data/YaNFD#51]
`nfdc face create ether://[98:28:A6:3B:86:02] local dev://ens3`

- nfdc returns `Error 406 when creating face: Unsupported scheme ether`

- YaNFD log contains `WARN[3207] [FaceMgmt] Unable to create ether face with URI ether://[98:28:A6:3B:86:02]: Unsupported scheme ether://[]`

**Comment by zjkmxy** [comment]
The current version of YaNFD only supports creating TCP and UDP faces after startup.
You may use the [yanfd.toml](https://github.com/named-data/YaNFD/blob/5bf27dad9034184e8704da2d7231dfee11f1b3db/yanfd.toml.sample#L19-L26) file to let YaNFD create the Ethernet face when starting up. 
I don't think I can add this feature because I lack devices to test.
People who are able to do so are welcome to submit Pull Requests.

**Comment by malldisaesar** [comment]
Can you tell me how to make face `ether` from `yanfd.toml` ?

**Comment by zjkmxy** [comment]
YaNFD supports multicast Ethernet face.
Set `faces.ethernet.enabled` to be true, put the multicast address, and YaNFD will create a face on every interface using that address.
There is no need to specify a host's MAC address or Ethernet interface.

**Comment by malldisaesar** [comment]
It will make looping packet when more than 2 node or not? Because on nfd forwarder it make looping when i'm add route to multicast id

**Comment by zjkmxy** [comment]
> It will make looping packet when more than 2 node or not? Because on nfd forwarder it make looping when i'm add route to multicast id

I don't think it will. There is Interest aggregation preventing it.

**Comment by zjkmxy** [comment]
The Ethernet face is removed in #62. Probably will be added back in future but let me close this issue for now.
